apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: keepalived
  namespace: kube-system
spec:
  containers:
  - image: harbor.jcudev.corp/keepalived/keepalived:0.0.1
    name: keepalived
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_BROADCAST
        - NET_RAW
    volumeMounts:
    - mountPath: /etc/keepalived/keepalived.conf
      name: config
    - mountPath: /etc/keepalived/check_apiserver.sh
      name: check
  hostNetwork: true
  volumes:
  - hostPath:
      path: /var/lib/rancher/rke2/keepalived/keepalived.conf
    name: config
  - hostPath:
      path: /var/lib/rancher/rke2/keepalived/check_apiserver.sh
    name: check
status: {}