apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "2"
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4xVTW/jNhD9K8WcZUf+3IRAD0Y3h0UbY7EOWhSLIBiRY5s1RQrDkbJGoP9eUF0nsuvEuVHzHt+8GZKjZ8DK/kkcbfCgAKsqXjUjyGBnvQEFn5HK4FckkEFJggYFQT0Deh8ExQYf02co/iEtkWTINgw1ijga2nBlkwZkb+LhyRMPNs0OFOwmsYc0o+yX3603vy6MCf6ihMeSkkZd0KCx1Yf4sUL9sinuo1AJbQaaqSvs3pYUBcsKlK+dy8BhQe7dcrcYt6DArK9ns6kh1Pn1elasi3l+Y/Kb6afc4Gg8nRospjiejlO2E+MDE+G/4BvuYkU6WYjkSEvgtC5R9PaPF3dnJNs2A6GycijU7egd5QfqfUPx4EUHL2g9cQT1/RmQN2kBJXrcEMNDBuSbDvop1NjqETmdUoOuTpE1ukjQZkcU64V4ndrwSnShz6oCSw+cT6eTUxFtDfcok3GfoKtH8li4fgbhmk44r+fxSjs+l6OUxvj4Xm2x0ZfTJqEoyOIIDfGlXqExFRFHCa64oOqCRpfIPV6hSQ90YDI+jtXoZjwcza+Ho8lkOJ+pUZ7neV+l2Hygb4nEoRZia07j2O/PfHZGPvlDY5hiPAdVeD7+MeE+6aTWbo9SXY+zI2z+DvbpCOunPNTwRsJraB8ysCVuuuvsvOGrwzNTTT6cDGfwE/9aO/c1OKv3oGDhnnB/GBXHg48phpo1pZebHinpmq3sfwte6Id07xUrLKyzYjtS8pje6/L2/nHx+e7LErJu/W3xF2Sw+nv1eP/l7hYe2jZ53YYoS5KnwDtQ6cwz8MHQqjeP0veAg6NhssWehGIajyVGIX69KhCJG6tpoXWovSz/V4oER3z4y3x/BlqvSQsoWIaV3pKpuwu4o9SRC0kzCFXSSg7h9oeNEqF9SFOsrgwKrYRRaLNPTUvOBKXumqNrZvKyrMuC+JDVgMozMBQtkzkH+S52Z2M8E/5GaPag8rb9NwAA//8pubk0fwcAAA
    objectset.rio.cattle.io/id: ""
    objectset.rio.cattle.io/owner-gvk: k3s.cattle.io/v1, Kind=Addon
    objectset.rio.cattle.io/owner-name: kube-vip
    objectset.rio.cattle.io/owner-namespace: kube-system
  creationTimestamp: "2021-08-06T15:02:27Z"
  generation: 2
  labels:
    objectset.rio.cattle.io/hash: df8554deac08f5bfb609d09470da1244dab4a242
  name: kube-vip-ds
  namespace: kube-system
  resourceVersion: "20612"
  uid: bee8aa39-99af-4215-9424-b19d16cf6a18
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: kube-vip-ds
    spec:
      containers:
      - args:
        - manager
        env:
        - name: bgp_routerinterface
          value: ens192
        - name: vip_arp
          value: "false"
        - name: vip_interface
          value: lo
        - name: port
          value: "6443"
        - name: vip_cidr
          value: "32"
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: vip_ddns
          value: "false"
        - name: svc_enable
          value: "true"
        - name: vip_startleader
          value: "false"
        - name: vip_addpeerstolb
          value: "true"
        - name: vip_localpeer
          value: bcec-coredns2:192.168.133.65:10000
        - name: bgp_enable
          value: "true"
        - name: bgp_routerid
        - name: bgp_as
          value: "65000"
        - name: bgp_peeraddress
        - name: bgp_peerpass
        - name: bgp_peeras
          value: "65000"
        - name: bgp_peers
          value: 192.168.133.65:65000::false,192.168.133.66:65000::false,192.168.133.67:65000::false
        - name: address
          value: 192.168.133.68
        image: plndr/kube-vip:v0.3.5
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_TIME
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kube-vip
      serviceAccountName: kube-vip
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 3
  desiredNumberScheduled: 3
  numberAvailable: 3
  numberMisscheduled: 0
  numberReady: 3
  observedGeneration: 2
  updatedNumberScheduled: 3