apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-coredns
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      volumes:
        items:
          - key: asteroids.db
            path: asteroids.db
      config: 
        asteroids.db: | -
    ";$TTL  30M
    @   IN  SOA  bm1.tdc4.corp.  tdc4.corp.  (
                    2019041900  ; Serial
                    4H          ; Refresh
                    1H          ; Retry
                    7D          ; Expire
                    4H )        ; Negative Cache TTL
        IN  NS  bm1

    bm1     IN  A   10.10.4.1
    bm2     IN  A   10.10.4.2
    bm3     IN  A   10.10.4.3
    bm4     IN  A   10.10.4.4
    vip.tdc4.corp.     IN  A   10.10.4.5
    rancher-lb.tdc4.corp.     IN  A   10.10.4.21

    *.vip.tdc4.corp.     IN  CNAME   vip
    rancher.tdc4.corp.     IN  CNAME   rancher-lb"
